### ISSUE TITLE
Discursão sobre o tema do projeto

### ISSUE THREAD

**Issue by FilipeNMarques** [FilipeNMarques/projeto-ead-pernambuco#2]
A minha ideia inicial é: Um site que liste conteúdos de tecnologia. 

Daí poderíamos fazer tipo um portal, que tenha categorias, temas, artigos e etc.
E depois que já tiver um front bacana, implantaríamos um backend em alguma linguagem legal para quem quiser, poder participar também
Já sabemos que nu curso iremos utilizar HTML, CSS, Javascript e Bootstrap.

**Comment by Carine-Neris** [comment]
Achei legal a ideia mas acho que para começo seria bom algo mais simples e fácil como criar alguma página estática e depois, num segundo momento, partir para um portal, fazer o deploy e podemos deixar ele no ar com conteúdos do curso e tal para ajudar novos alunos do curso.

**Comment by FranciscoBernardo** [comment]
Legal a idéia. Estou dentro

**Comment by Ernanidacosta** [comment]
Tô por aqui.

**Comment by claudiobernardo** [comment]
Opa, legal a ideia. Seria como um blog de notícias?

**Comment by FilipeNMarques** [comment]
Isso mesmo Cláudio.

**Comment by EduAlexandre** [comment]
Tá ótimo para começar. E como será o andamento, tipo início, quem vai fazer o que, vai rolar scrum... ?

**Comment by claudiobernardo** [comment]
Seria muito bom Alexandre, ter Scrum, só assim aprenderiamos na prática.

**Comment by FilipeNMarques** [comment]
Sim, com certeza pessoal, seria muito interessante fazer agile no nosso projeto. Mas como vamos começar aos poucos. Poderíamos abrir uma issue sobre conteúdos que podemos passar para o pessoal. Fazendo assim, podemos aumentar o conhecimento da galera...

**Comment by laerciosoares** [comment]
Estou dentro,Legal vamos por a mão na massa

**Comment by FilipeNMarques** [comment]
> Estou dentro,Legal vamos por a mão na massa

Show! Vamos nessa! :D

**Comment by FilipeNMarques** [comment]
Ideia do projeto inicial fechada. Vamos utilizar essa ideia aqui num segundo momento.
