### ISSUE TITLE
Tutores, leiam isso! :D 

### ISSUE THREAD

**Issue by FilipeNMarques** [FilipeNMarques/projeto-ead-pernambuco#3]
Amigos, primeiramente, gostaria de agradecer por vocês doarem seu tempo para comunidade. Fico muito feliz em poder ajudar também! 

Vamos lá, inicialmente vamos precisar saber como cada um vai poder ajudar no projeto. 

Que tenologias você sabe? 
Quer passar algum conteúdo para o pessoal? 
Tem alguma experiencia com gerenciamento de projetos?

Uma coisa que eu acho fundamental é ter tasks para todos os níveis de conhecimento, por favor vamos garantir que todos que se inscreveram vão contribuir! Isso vai ser muito importante e no final, com certeza vai nos orgulhar! 

Enfim, acho que é isso, qualquer coisa vão passando por aqui um feedback para mantermos nosso projeto bem organizado e colaborativo! 

Grande abraço e vamos nessa! :D

**Comment by Carine-Neris** [comment]
Olá Filipe, fico muito grata em poder compartilhar um pouco do que aprendi até agora.
Em relação as suas perguntas eu tenho conhecimento em html, css e um pouco de JS. 
Acho interessante, antes de dar andamento no projeto, reforçar um pouco da lógica de programação e procurar saber se todos estão familiarizados com o git e github.
Em relação a gerenciamento de projeto ainda não possuo experiência.

**Comment by claudiobernardo** [comment]
Concordo com @Carine-Neris, é bom saber se todos estão familiarizados com Git e Github, porque sem essas skills as contribuições não vão andar.

**Comment by FilipeNMarques** [comment]
É isso mesmo pessoal, foi por isso que eu fiz aquela live falando sobre isso... 

Mas de qualquer forma, vamos passando na prática para o pessoal! :D 

Estamos juntos!
