### ISSUE TITLE
Ideia de projeto

### ISSUE THREAD

**Issue by Carine-Neris** [FilipeNMarques/projeto-ead-pernambuco#4]
Achei legal a ideia mas acho que para começo seria bom algo mais simples e fácil como criar alguma página estática e depois, num segundo momento, partir para um portal, fazer o deploy e podemos deixar ele no ar com conteúdos do curso e tal para ajudar novos alunos do curso.

**Comment by FilipeNMarques** [comment]
Verdade, não tinha pensado por esse lado. Diz um tema legal para essa página... E levamos para votação.

**Comment by Carine-Neris** [comment]
pode ser algo tipo um portfolio porém mais simples do que esses que a galera faz por ai, ou sobre alguma outra coisa que a galera achar interessante.

**Comment by Ernanidacosta** [comment]
Também acho interessante começar bem do básico mesmo, esqueleto e ir dando volume aos poucos.

**Comment by claudiobernardo** [comment]
Boa ideia @Carine-Neris

**Comment by FilipeNMarques** [comment]
Ideia fechada, vamos criar inicialmente um currículo usando apenas html e css
